[package]
name = "cryss"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
hound = "3.4.0"
num = "0.4.0"
rand = "0.8.3"
